import { Destination, Accommodation, Restaurant, Transport } from '@/types';

export const destinations: Destination[] = [
  {
    id: '1',
    name: 'Mont Cameroun',
    description: 'Le plus haut sommet d\'Afrique de l\'Ouest, offrant des randonnées spectaculaires et des vues panoramiques.',
    image: '/assets/mont_cameroun.jpg',
    region: 'Région du Sud-Ouest',
    price: 150000,
    rating: 4,
    activities: ['Randonnée', 'Camping', 'Observation'],
    accommodations: [
      { name: 'Fini Hotel', type: 'Hôtel', price: 80000 },
      { name: 'Mountain Hotel', type: 'Hôtel', price: 60000 }
    ],
    restaurants: [
      { name: 'Savoy Restaurant', cuisine: 'Internationale', priceRange: 'Élevé' },
      { name: 'Mountain Hotel Restaurant', cuisine: 'Locale', priceRange: 'Modéré' }
    ],
    transports: []
  },
  {
    id: '2',
    name: 'Chutes de la Lobé',
    description: 'Des cascades uniques qui se jettent directement dans l\'océan Atlantique.',
    image: '/assets/chutes_lobe_kribi.jpg',
    region: 'Kribi',
    price: 75000,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  },
  {
    id: '3',
    name: 'Parc National de Waza',
    description: 'Safari exceptionnel dans la savane camerounaise avec une faune diversifiée.',
    image: '/assets/parc_waza_elephants.jpg',
    region: 'Région de l\'Extrême-Nord',
    price: 200000,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  },
  {
    id: '4',
    name: 'Palais Royal de Foumban',
    description: 'Patrimoine culturel exceptionnel du royaume Bamoun.',
    image: '/assets/palais_royal_foumban.jpg',
    region: 'Foumban',
    price: 50000,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  },
  {
    id: '5',
    name: 'Chutes d\'Ekom Nkam',
    description: 'Magnifiques cascades de 80 mètres de hauteur dans la forêt tropicale.',
    image: '/assets/ekom_nkam.jpg',
    region: 'Région du Littoral',
    price: 80000,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  },
  {
    id: '6',
    name: 'Réserve de Faune du Dja',
    description: 'Site du patrimoine mondial de l\'UNESCO, riche en biodiversité.',
    image: '/assets/reserve_dja_foret.jpg',
    region: 'Région du Sud',
    price: 180000,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  },
  {
    id: '7',
    name: 'Rhumsiki',
    description: 'Paysages lunaires spectaculaires et culture traditionnelle Kapsiki.',
    image: '/assets/roches_mvouto.jpg',
    region: 'Région de l\'Extrême-Nord',
    price: 120000,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  },
  {
    id: '8',
    name: 'Lac Baleng',
    description: 'Lac de cratère mystique entouré de légendes locales.',
    image: '/assets/lac_baleng_peche.jpg',
    region: 'Région de l\'Ouest',
    price: 60000,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  },
  {
    id: '9',
    name: 'Phare de Kribi',
    description: 'Phare historique offrant une vue imprenable sur la côte atlantique.',
    image: '/assets/phare_kribi.jpg',
    region: 'Kribi',
    price: 40000,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  },
  {
    id: '10',
    name: 'Mont Manengouba et Lacs Jumeaux',
    description: 'Volcan endormi avec des lacs de cratère aux eaux de couleurs différentes.',
    image: '/assets/lacs_jumeaux_manengouba.jpg',
    region: 'Région du Littoral',
    price: 100000,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  }
  ,
  {
    id: '11',
    name: 'The Botanic Garden - Limbé',
    description: 'Jardin botanique historique avec flore exceptionnelle et sentiers ombragés.',
    image: '/assets/botanic_garden_limbe.jpg',
    region: 'Limbé',
    price: 60000,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  },
  {
    id: '12',
    name: 'Le Domaine de Petpenoun',
    description: 'Eco-lodge au bord du lac avec activités nautiques et de plein air.',
    image: '/assets/domaine_petpenoun.jpg',
    region: 'Kouoptamo (Ouest)',
    price: 90000,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  },
  {
    id: '13',
    name: 'Lamidat de Ngaoundéré',
    description: 'Chefferie traditionnelle peule, patrimoine culturel et architecture remarquable.',
    image: '/assets/lamidat_ngaoundere.jpg',
    region: 'Ngaoundéré (Adamaoua)',
    price: 50000,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  },
  {
    id: '14',
    name: 'Musée National',
    description: 'Ancien palais présidentiel devenu musée sur l’histoire du Cameroun.',
    image: '/assets/musee_national_yaounde.jpg',
    region: 'Yaoundé (Centre)',
    price: 30000,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  },
  {
    id: '15',
    name: 'Musée Maritime',
    description: 'Musée moderne dédié au patrimoine maritime du Cameroun.',
    image: '/assets/musee_maritime_exterieur.jpg',
    region: 'Douala (Littoral)',
    price: 25000,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  },
  {
    id: '16',
    name: 'Parc National de Korup',
    description: 'Forêt tropicale ancienne, biodiversité remarquable.',
    image: '/assets/pont_singes_ekom.jpg',
    region: 'Sud-Ouest',
    price: 120000,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  },
  {
    id: '17',
    name: 'Gorges de Kola',
    description: 'Gorges spectaculaires et piscines naturelles.',
    image: '/assets/gorges_kola.jpg',
    region: 'Guider (Nord)',
    price: 70000,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  },
  {
    id: '18',
    name: 'Monument de la Réunification',
    description: 'Symbole de l’unité nationale à Yaoundé.',
    image: '/assets/monument_reunification_yaounde.jpg',
    region: 'Yaoundé (Centre)',
    price: 20000,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  },
  {
    id: '19',
    name: 'Grotte Fovu',
    description: 'Site naturel et culturel de Baham.',
    image: '/assets/grotte_fovu.jpg',
    region: 'Baham (Ouest)',
    price: 40000,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  },
  {
    id: '20',
    name: 'La Nouvelle Liberté',
    description: 'Sculpture monumentale au rond-point Deïdo.',
    image: '/assets/nouvelle_liberte_douala.jpg',
    region: 'Douala (Littoral)',
    price: 0,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  },
  {
    id: '21',
    name: 'Monument Natchigal',
    description: 'Monument historique de Douala.',
    image: '/assets/obelisque_limbe.jpg',
    region: 'Douala (Littoral)',
    price: 0,
    rating: 4,
    activities: [],
    accommodations: [],
    restaurants: [],
    transports: []
  }
];

export const accommodations: Accommodation[] = [
  { id: '1', name: 'Hôtel Sawa', type: 'hotel', pricePerNight: 85000, rating: 4, destinationId: '1' },
  { id: '2', name: 'Lodge Mont Cameroun', type: 'lodge', pricePerNight: 65000, rating: 3, destinationId: '1' },
  { id: '3', name: 'Hôtel Ilomba', type: 'hotel', pricePerNight: 70000, rating: 4, destinationId: '2' },
  { id: '4', name: 'Auberge de Kribi', type: 'guesthouse', pricePerNight: 45000, rating: 3, destinationId: '2' },
  { id: '5', name: 'Campement Waza', type: 'lodge', pricePerNight: 90000, rating: 3, destinationId: '3' },
  { id: '6', name: 'Hôtel Sahel', type: 'hotel', pricePerNight: 75000, rating: 4, destinationId: '3' },
  { id: '7', name: 'Palais des Hôtes', type: 'hotel', pricePerNight: 60000, rating: 4, destinationId: '4' },
  { id: '8', name: 'Auberge Bamoun', type: 'guesthouse', pricePerNight: 35000, rating: 3, destinationId: '4' }
  ,
  { id: '9', name: 'Seme Beach Hotel', type: 'hotel', pricePerNight: 80000, rating: 4, destinationId: '11' },
  { id: '10', name: 'Park Hotel Mirama', type: 'hotel', pricePerNight: 70000, rating: 4, destinationId: '11' },
  { id: '11', name: 'Le Domaine de Petpenoun', type: 'lodge', pricePerNight: 90000, rating: 4, destinationId: '12' },
  { id: '12', name: 'Adamaoua Hotel', type: 'hotel', pricePerNight: 60000, rating: 4, destinationId: '13' },
  { id: '13', name: 'Vina Hotel', type: 'hotel', pricePerNight: 55000, rating: 3, destinationId: '13' },
  { id: '14', name: 'Hôtel Mont Fébé', type: 'hotel', pricePerNight: 90000, rating: 4, destinationId: '14' },
  { id: '15', name: 'Hilton Hotel', type: 'hotel', pricePerNight: 140000, rating: 5, destinationId: '14' },
  { id: '16', name: 'StarLand Hotel', type: 'hotel', pricePerNight: 120000, rating: 4, destinationId: '15' },
  { id: '17', name: 'Hôtel La Falaise', type: 'hotel', pricePerNight: 110000, rating: 4, destinationId: '15' },
  { id: '18', name: 'Korup Rainforest Camp', type: 'lodge', pricePerNight: 40000, rating: 3, destinationId: '16' },
  { id: '19', name: 'Hôtel La Bénoué', type: 'hotel', pricePerNight: 50000, rating: 3, destinationId: '17' },
  { id: '20', name: 'Djeuga Palace', type: 'hotel', pricePerNight: 100000, rating: 4, destinationId: '18' },
  { id: '21', name: 'Hôtel Azur', type: 'hotel', pricePerNight: 70000, rating: 3, destinationId: '18' },
  { id: '22', name: 'Hôtel Mbatkam Palace', type: 'hotel', pricePerNight: 60000, rating: 4, destinationId: '19' },
  { id: '23', name: 'Akwa Palace', type: 'hotel', pricePerNight: 110000, rating: 4, destinationId: '20' },
  { id: '24', name: 'SAWA Hotel', type: 'hotel', pricePerNight: 100000, rating: 4, destinationId: '20' },
  { id: '25', name: 'Hôtel Le Phare', type: 'hotel', pricePerNight: 60000, rating: 3, destinationId: '9' },
  { id: '26', name: 'Hôtel Le Château', type: 'hotel', pricePerNight: 80000, rating: 3, destinationId: '21' }
];

export const restaurants: Restaurant[] = [
  { id: '1', name: 'Restaurant Panorama', cuisine: 'Camerounaise', pricePerMeal: 15000, rating: 4, destinationId: '1' },
  { id: '2', name: 'Chez Mama Africa', cuisine: 'Locale', pricePerMeal: 12000, rating: 4, destinationId: '1' },
  { id: '3', name: 'Le Homard Bleu', cuisine: 'Fruits de mer', pricePerMeal: 18000, rating: 5, destinationId: '2' },
  { id: '4', name: 'Restaurant de la Plage', cuisine: 'Internationale', pricePerMeal: 14000, rating: 4, destinationId: '2' },
  { id: '5', name: 'Savane Grill', cuisine: 'Grillades', pricePerMeal: 16000, rating: 4, destinationId: '3' },
  { id: '6', name: 'Chez Hadja', cuisine: 'Nordiste', pricePerMeal: 10000, rating: 4, destinationId: '3' },
  { id: '7', name: 'Restaurant Royal', cuisine: 'Traditionnelle', pricePerMeal: 13000, rating: 4, destinationId: '4' },
  { id: '8', name: 'Le Bamoun', cuisine: 'Locale', pricePerMeal: 11000, rating: 3, destinationId: '4' }
  ,
  { id: '9', name: 'Le Panoramique', cuisine: 'Internationale', pricePerMeal: 20000, rating: 4, destinationId: '11' },
  { id: '10', name: 'The LK Restaurant', cuisine: 'Locale', pricePerMeal: 15000, rating: 4, destinationId: '11' },
  { id: '11', name: 'Restaurant du Domaine', cuisine: 'Locale', pricePerMeal: 18000, rating: 4, destinationId: '12' },
  { id: '12', name: 'La Plazza Restaurant', cuisine: 'Internationale', pricePerMeal: 16000, rating: 4, destinationId: '13' },
  { id: '13', name: 'Restaurant La Salsa', cuisine: 'Internationale', pricePerMeal: 20000, rating: 4, destinationId: '14' },
  { id: '14', name: 'Restaurant 5 Fourchettes', cuisine: 'Gastronomique', pricePerMeal: 30000, rating: 5, destinationId: '15' },
  { id: '15', name: 'LA CASA', cuisine: 'Locale', pricePerMeal: 14000, rating: 4, destinationId: '17' },
  { id: '16', name: 'Restaurant Platinium', cuisine: 'Internationale', pricePerMeal: 22000, rating: 4, destinationId: '17' },
  { id: '17', name: 'Seven Hills', cuisine: 'Internationale', pricePerMeal: 25000, rating: 4, destinationId: '18' },
  { id: '18', name: 'Socrat Restaurant', cuisine: 'Locale', pricePerMeal: 18000, rating: 4, destinationId: '18' },
  { id: '19', name: 'Restaurant Ômulema', cuisine: 'Locale', pricePerMeal: 15000, rating: 4, destinationId: '19' },
  { id: '20', name: 'Complexe les Palétuviers', cuisine: 'Locale', pricePerMeal: 20000, rating: 4, destinationId: '20' },
  { id: '21', name: 'Le Touloulou', cuisine: 'Fruits de mer', pricePerMeal: 25000, rating: 4, destinationId: '2' },
  { id: '22', name: 'Le Calypso-Kribi', cuisine: 'Internationale', pricePerMeal: 20000, rating: 4, destinationId: '2' },
  { id: '23', name: 'Maison H', cuisine: 'Gastronomique', pricePerMeal: 30000, rating: 5, destinationId: '21' },
  { id: '24', name: 'Restaurant La Fourchette', cuisine: 'Internationale', pricePerMeal: 22000, rating: 4, destinationId: '21' }
];

export const transports: Transport[] = [
  { id: '1', type: 'car', name: 'Location 4x4', price: 50000, destinationId: '1' },
  { id: '2', type: 'bus', name: 'Transport en commun', price: 15000, destinationId: '1' },
  { id: '3', type: 'car', name: 'Taxi privé', price: 35000, destinationId: '2' },
  { id: '4', type: 'bus', name: 'Bus touristique', price: 20000, destinationId: '2' },
  { id: '5', type: 'plane', name: 'Vol domestique', price: 120000, destinationId: '3' },
  { id: '6', type: 'car', name: 'Location véhicule', price: 45000, destinationId: '3' },
  { id: '7', type: 'car', name: 'Transport privé', price: 40000, destinationId: '4' },
  { id: '8', type: 'bus', name: 'Bus régional', price: 18000, destinationId: '4' }
];